### ISSUE TITLE
Add discord community servers feature

### ISSUE THREAD

**Issue by odiffey** [DogcraftNet/Dogcraft-Website-Issues#15]
Allow users to view a page of invites with info, links, primary contacts, etc, submit reports against servers, and request servers to add to list.
Admins/mods should be able to manage servers in the list and handle requests and reports

**Comment by domino-1** [comment]
The [DiscordInvites MW extension](https://github.com/domino-1/MWDiscordInvites) will be able to handle something like this. Currently it already has a config option for setting pages exempt from most security checks (such as anything making a call to the Discord API) which can be used for admin-protected pages with containing a lot of invites.
